# Rime default settings
# encoding: utf-8

config_version: '0.40'

schema_list:
  - schema: flypy_flypy # 小鹤+鹤形
  - schema: flypy_moqi # 小鹤+墨奇
  - schema: japanese
  - schema: melt_eng

switcher:
  caption: 〔方案選單〕
  hotkeys:
    # - Control+grave
    # - Control+Shift+grave
    # - F4
    - Control+Shift+space
  save_options:
    - ascii_mode
    - full_shape
    - emoji
    - simplification
    - ascii_punct
  fold_options: true
  abbreviate_options: true
  option_list_separator: '〔方案選單〕'

menu:
  page_size: 5

punctuator:
  import_preset: symbols

key_binder:
  bindings:
    - { when: has_menu, accept: Control+j, send: Down }      # vim 风格选词
    - { when: has_menu, accept: Control+k, send: Up }        # vim 风格选词
    - { when: has_menu, accept: Control+h, send: Page_Up }   # vim 风格选词
    - { when: has_menu, accept: Control+l, send: Page_Down } # vim 风格选词

    # 翻页 - =
    - { when: has_menu, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    # 翻页 Tab
    # - { when: has_menu, accept: Shift+Tab, send: Up }
    # - { when: has_menu, accept: Tab, send: Down }
    # 翻页 [ ]
    - { when: paging, accept: bracketleft, send: Page_Up }
    - { when: has_menu, accept: bracketright, send: Page_Down }

    # 将小键盘 0~9 . + - * / 映射到主键盘
    # 使计算器(V1+2*3)可使用小键盘输入
    # 数字金额大写的 Lua 如 R1234.5678 可使用小键盘输入
    - {accept: KP_0, send: 0, when: composing}
    - {accept: KP_1, send: 1, when: composing}
    - {accept: KP_2, send: 2, when: composing}
    - {accept: KP_3, send: 3, when: composing}
    - {accept: KP_4, send: 4, when: composing}
    - {accept: KP_5, send: 5, when: composing}
    - {accept: KP_6, send: 6, when: composing}
    - {accept: KP_7, send: 7, when: composing}
    - {accept: KP_8, send: 8, when: composing}
    - {accept: KP_9, send: 9, when: composing}
    - {accept: KP_Decimal,  send: period  , when: composing}
    - {accept: KP_Multiply, send: asterisk, when: composing}
    - {accept: KP_Add,      send: plus,     when: composing}
    - {accept: KP_Subtract, send: minus,    when: composing}
    - {accept: KP_Divide,   send: slash,    when: composing}

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: commit_code   # 按 shift 键，已输入字符上屏，同时切换为英文输入
    Shift_R: commit_code
    Control_L: noop        # 无操作
    Control_R: noop
    Caps_Lock: clear       # 按大小写切换键，清除已输入字符，同时切换为英文输入
